# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-09 05:33
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191208_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to=core.models.user_directory_path)),
                ('content', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('ST', 'Shortlisted'), ('RT', 'Rejected')], default='PE', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(blank=True, max_length=50)),
                ('stipend', models.IntegerField(blank=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('allowances', models.CharField(blank=True, max_length=150)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_details', to='core.StartUps')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='intern_pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='core.InternDetails'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='core.Students'),
        ),
    ]
