# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-13 13:41
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191211_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='startups',
            name='logo',
            field=models.ImageField(blank=True, upload_to=core.models.user_directory_path),
        ),
    ]
