# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-04 10:08
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_startups_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interndetails',
            name='stipend',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='startups',
            name='logo',
            field=models.ImageField(blank=True, upload_to=core.models.user_directory_path1),
        ),
    ]
