# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-04 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200104_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='phone_number',
            field=models.IntegerField(default=8319813212),
            preserve_default=False,
        ),
    ]
