# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-04 16:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200104_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9876543210'. Up to 10 digits allowed.", regex='^\\d{9,10}$')]),
        ),
    ]
