# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-06 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200104_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='startups',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
